import Head from "next/head";
// import Image from "next/image";
import { Inter, Patrick_Hand } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Header from "@/component/header";
import FirstPage from "@/component/firstPage";

const inter = Inter({ subsets: ["latin"] });
const partickHand = Patrick_Hand({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Aisosa Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className={partickHand.className} />
      <main className={`${styles.main} ${partickHand.className}`}>
        <FirstPage />
      </main>
    </>
  );
}
